apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ws-ingress
  labels:
    app.kubernetes.io/name: chat-ws-ingress
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: chat-ws-service
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  rules:
  - host: ai-companion-chat.com
    http:
      paths:
      - pathType: Prefix
        path: /ws
        backend:
          service:
            name: chat-ws-service
            port: 
              number: 3002
