apiVersion: v1
kind: Secret
metadata:
  name: ai-consumer-secret
type: Opaque
data:
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  GOOGLE_API_KEY: QUl6YVN5QUVHUG80MWVHWFNWb1hHaEF1RUpLcUV4VFV0ZUE5Vm8w