apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-companion-gateway-configmap
data:
  AUTH_SVC_ADDR: "ai-companion-auth-service:3001"
  AI_CHAR_SVC_ADDR: "ai-character-service:3000"
  LOG_LEVEL: "info"
