apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-gateway-ingress
  labels:
    app.kubernetes.io/name: chat-app-gateway-ingress
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
  - host: ai-companion-chat.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ai-companion-gateway-service
            port: 
              number: 3003
  