apiVersion: v1
kind: Service
metadata:
  name: ai-companion-gateway-service
spec:
  selector:
    app: ai-companion-gateway
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 5000
    protocol: TCP
