apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-dispatcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-dispatcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: message-dispatcher
    spec:
      containers:
      - name: message-dispatcher
        image: deveshk237572/message-dispatcher:latest
        envFrom:
          - configMapRef:
              name: message-dispatcher-configmap
          - secretRef:
              name: message-dispatcher-secret
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8005
