apiVersion: v1
kind: Secret
metadata:
  name: ai-companion-auth-secret
type: Opaque
data:
  JWT_SECRET: NjE1ODdkMWYxYjExMzllNTkwNjEwNjhjZjMzZTQ2ZTVmNmIwOGE5MWFkYjZmMWFkNDAyODRhYzEwN2Q5ZTFlOQ==
  DB_PASSWORD: Y2hhdF9wYXNzd29yZA==
